### ISSUE TITLE
[Todo]: Todo.txt as TODO

### ISSUE THREAD

**Issue by eri47** [LCLPYT/GoethePlaner#9]
**Describe the task**:
(describe here)

**Task list** (optional, delete if unnecissary):
- [ ] Eindeutig zeigen, wann die App etwas lädt (mit progress-bar)
- [ ] Offline-Modus hinzufügen -> data persistence
- [ ] Trotzdem den Content ASAP zeigen -> Letzte Vertretungen aus Offline-Modus mit Ladesymbol anzeigen, danach austauschen
- [ ] 
- [ ] 
- [ ]
